### ISSUE TITLE
It needs to fix version of lagom sbt plugin

### ISSUE THREAD

**Issue by eovechkin** [lagom/online-auction-scala#1]
Hello,

It needs to fix version of "lagom-sbt-plugin" in "project/plugins.sbt" from "1.3.0-SNAPSHOT" to "1.3.0-M1".

Thx.

**Comment by xpavlic4** [comment]
The same here:

[error] (*:update) sbt.ResolveException: unresolved dependency: com.lightbend.lagom#lagom-sbt-plugin;1.3.0-SNAPSHOT: not found
(*:update) sbt.ResolveException: unresolved dependency: com.lightbend.lagom#lagom-sbt-plugin;1.3.0-SNAPSHOT: not found
> load-failed
Failed to load project.
