### ISSUE TITLE
online-auction-scala is missing in Travis CI - lagom space

### ISSUE THREAD

**Issue by thrxde** [lagom/online-auction-scala#15]
add project to [https://travis-ci.org/lagom]( https://travis-ci.org/lagom) for automatically build, pease

**Comment by Lambrina** [comment]
Hi, I just tried to do this but got the following message : "You don't have sufficient rights to enable this repo on Travis.Please contact the admin to enable it or to receive admin rights yourself."

**Comment by ignasi35** [comment]
Thanks @Lambrina I suspect this is can't be solved by non-members. I'll remove the `outreachy` label.

**Comment by TimMoore** [comment]
Sorry, I didn't realize that there was already a `.travis.yml` in the project and it just needed to be enabled on the Travis side!

**Comment by TimMoore** [comment]
I have enabled this project in Travis CI: https://travis-ci.org/lagom/online-auction-scala

It's currently still awaiting the first build.
