### ISSUE TITLE
Enable MetricsService

### ISSUE THREAD

**Issue by TimMoore** [lagom/online-auction-scala#16]
It wasn't obvious to me that `MetricsService` is opt-in with the Scala API, vs. automatic with Java.

We should demonstrate how to include it in the search service (which is the only Lagom service in this project that makes service calls): http://www.lagomframework.com/documentation/1.3.x/scala/ServiceClients.html#circuit-breaker-metrics

**Comment by katejim** [comment]
I would like to fix this

**Comment by TimMoore** [comment]
This is obsolete, since Lagom 1.3.3. See https://github.com/lagom/lagom/pull/637
