### ISSUE TITLE
sbt-eclipse creates descriptors for transaction-xyz causing errors

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-scala#22]
When forking the `online-auction-java` some java left-over code was left on `transaction-api`. `sbt` does a good job at ignoring it because the `lazy val root` doesn't include `transaction-xxx` as project modules (see `aggregate`).

`sbt-eclipse`, on the other hand, creates Eclipse descriptors for both `transaction-xxx` which are not compiling at the moment (plus, use Java instead of Scala), so when importing into Eclipse there are compilation errors there.

There are several options here:

 * cleanup transactions code (remove java code)
 * configure sbt-eclipse to honour the `root` project setup
 * update README and instruct users to _not_ import `transactions-xxx` (see #24)

**Comment by TimMoore** [comment]
I think it would be better to either port the transactions code to Scala or remove it, rather than leaving it there but excluding it from Eclipse. WDYT?

**Comment by ignasi35** [comment]
Just seen you comment after merging #26 which adopted option (2) on the list in the description of this issue. With that merged, eclipse users won't see `transactions-xxx` in the IDE. The first thing a developer taking over the task to implement `transactions-xxx` will have to do is remove the ignores.

To answer your question, I don't think porting incomplete java code to scala makes sense. Removing sounds very reasonable. At same time, removing the code would, sort of, break parity. Even if the current code does nothing. Oh, my...

TBH, we now have an example of how to skip a subproject from eclipse to Id' stay with that until we develop the feature (and would push for the feature to be developed sooner rather than later).

**Comment by ignasi35** [comment]
The actual issue is no longer manifesting (fixed in #26). I'll close it.
