### ISSUE TITLE
TransactionApi seems getting a wrong dependency?

### ISSUE THREAD

**Issue by scweang** [lagom/online-auction-scala#44]
It use java dsl, but in build.sbt it's `lagomScaladslApi`?

**Comment by yg-apaza** [comment]
Transaction service is a work in progress. I updated the documentation to state this (#45)
Currently, the source code in `transaction-api` and `transaction-impl` is a copy of Online Auction Java. @ignasi35 @TimMoore do you think it's also necessary to remove the transactions code?

**Comment by TimMoore** [comment]
@yg-apaza if it's just a copy of the Java code, then yes please go ahead and remove it for now. It's only going to confuse people. Once the Java example is complete, we can port it over to Scala.

**Comment by scweang** [comment]
Thank you for quick response. I'm learning Lagom now. This demo is really useful for me.

**Comment by TimMoore** [comment]
Fixed in #46
