### ISSUE TITLE
Execution exception on startup + http://localhost:9000/ (root uri)

### ISSUE THREAD

**Issue by jewelsjacobs** [lagom/online-auction-scala#49]
I downloaded the latest master as a zip file, ran the sbt command, runAll then entered http://localhost:9000/ in Safari.

I'm running:

- macOS Sierra version 10.12.6
- sbt 0.13.15

I received a number of warnings followed by: 

```
Execution exception
[$anon$1: Circuit Breaker Timed out.]
```

I put the console log in a public gist since it was pretty large: https://gist.github.com/jewelsjacobs/6da1aea77c88e1107a9e1be92844bde3#file-startup-errors

For more info I set the sbt log to debug. I'm guessing it's related to Akka which I know nothing about.  Here is the even larger debug log: https://gist.github.com/jewelsjacobs/ede36b361b02f2e31547c449e7ffbf6e#file-debug-log

**Comment by jewelsjacobs** [comment]
This looks like it's happened before but then was resolved? https://github.com/lagom/online-auction-scala/issues/33 

@odwrotnie do you mind sharing how you resolved this?

**Comment by ignasi35** [comment]
Hi @jewelsjacobs are you able to reproduce the error? Have you tried deleting the  `/target` folder and restarting?

I'm trying the steps you described but can't reproduce the symptoms you describe. It's annoying because when @odwrotnie reported #33 we couldn't reproduce the error either. #meh

**Comment by jewelsjacobs** [comment]
I deleted all of the target directories (root app folder and all services directories). Same result. 😬 

I did managed to get rid of, on sbt, runAll, the compile warnings by running:

```
$ sbt clean
$ sbt test
```
before hand
But still got the NetworkClient warnings (on sbt, runAll) and the Circuit Breaker Timed out exception error on entering http://localhost:9000/ (browser cache cleared)

Java info:
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

console log:
```
 ~/D/s/online-auction-scala-master  sbt
[info] Loading global plugins from /Users/juliajacobs/.sbt/0.13/plugins
[info] Loading project definition from /Users/juliajacobs/Desktop/scalaApps/online-auction-scala-master/project
[info] Set current project to online-auction-scala (in build file:/Users/juliajacobs/Desktop/scalaApps/online-auction-scala-master/)
> runAll
[info] Updating {file:/Users/juliajacobs/Desktop/scalaApps/online-auction-scala-master/}lagom-internal-meta-project-kafka...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Starting Kafka
[info] Updating {file:/Users/juliajacobs/Desktop/scalaApps/online-auction-scala-master/}lagom-internal-meta-project-cassandra...
[info] Resolving org.slf4j#log4j-over-slf4j;1.7.7 ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Starting Cassandra
................
[info] Cassandra server running at 127.0.0.1:4000
[info] Updating {file:/Users/juliajacobs/Desktop/scalaApps/online-auction-scala-master/}lagom-internal-meta-project-service-locator...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Service locator is running at http://localhost:8000
[info] Service gateway is running at http://localhost:9000
[warn] o.a.k.c.NetworkClient - Error while fetching metadata with correlation id 1 : {bidding-BidEvent=LEADER_NOT_AVAILABLE}
[warn] o.a.k.c.NetworkClient - Error while fetching metadata with correlation id 1 : {item-ItemEvent=LEADER_NOT_AVAILABLE}
[info] Service itemImpl listening for HTTP on 0:0:0:0:0:0:0:0:53203
[info] Service userImpl listening for HTTP on 0:0:0:0:0:0:0:0:56181
[info] Service biddingImpl listening for HTTP on 0:0:0:0:0:0:0:0:58427
[info] Service webGateway listening for HTTP on 0:0:0:0:0:0:0:0:60496
[info] Service searchImpl listening for HTTP on 0:0:0:0:0:0:0:0:55320
[info] (Services started, press enter to stop and go back to the console...)
[error] application -

! @7512fogam - Internal server error, for (GET) [/] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[$anon$1: Circuit Breaker Timed out.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.```

**Comment by jewelsjacobs** [comment]
Fixed.  Here's what I did:

I forgot to install an run Elastisearch server (next time I'll read ALL of the instructions. I did that.

I STILL got the same exact problems though:

NetworkClient warnings (on sbt, runAll) and the Circuit Breaker Timed out exception error on entering http://localhost:9000/ (browser cache cleared).

However when I hit the enter after http://localhost:9000/ (browser refresh, not cache refresh) the site came up.

**Comment by jewelsjacobs** [comment]
Also wanted to mention the Circuit Breaker Timed out exception happened for me on pretty much every page, requiring a refresh, then until I got a user to successfully enter an item. After that it was smooth sailing. No Circuit Breaker Timed out exception on any additional pages any more.

**Comment by ignasi35** [comment]
Hi @jewelsjacobs running ElasticSearch is optional. It will cause the search features to return 0 results but the purpose of it being optional is to ease the run of the sample app and to show that in case of an partial infrastructure failure (in this case the DB of a particular microservice) the application continues to operate normally (but with some features degraded or temporarily unavailable, in this case the search forms).

I think that running  ElasticSearch is unrelated to the issue being fixed (I only start ES very rarely).

**Comment by ignasi35** [comment]
Thanks for all the information provided. It'll be helpful if the issue arises in the future.

**Comment by andrewayres** [comment]
Hi @jewelsjacobs - I experience exactly the same issue and exactly as you describe it.

**Comment by TimMoore** [comment]
@jewelsjacobs & @andrewayres I wonder if you might be affected by this bug with Java on Sierra: https://thoeni.io/post/macos-sierra-java/

This is known to cause slow startup in Lagom services and many other Java-based applications.

The workaround is described in that post, but the summary is:

1. `hostname | pbcopy` (copies your hostname)
2. `sudo -e /etc/hosts` (and enter your login password when prompted)
3. Paste your hostname at the end of the lines starting with `127.0.0.1` and `::1`
4. Save and exit your editor

For example, here is the final `/etc/hosts` file on my laptop:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
#127.0.0.1      localhost
127.0.0.1       localhost tmoore-lightbend.local
255.255.255.255 broadcasthost
#::1             localhost
::1             localhost tmoore-lightbend.local
```

**Comment by TimMoore** [comment]
BTW I just raised this issue to add a check to the Lagom development environment: https://github.com/lagom/lagom/issues/941

If is in fact the cause of the problems you've observed, that change might help future users troubleshoot it.

**Comment by andrewayres** [comment]
@TimMoore thank you so much for taking the time to look into this and post the above information. I can confirm this solved the problem for me; no more "Circuit Breaker Timed out" error and now online-auction-scala-master is lightning fast to run locally, instead of the sluggish responses I was getting before.

For reference, I'm running SierraOS 10.12.6 on a 2017 MBP running Java 1.8.0_144, and when running https://github.com/thoeni/inetTester I got a 5011ms response time. After adding my hostname to /etc/hosts in the way you describe above, it's now 6ms.

**Comment by ndelangen** [comment]
@TimMoore You saved my day, thank you so much! ♥️
