### ISSUE TITLE
Duplication of events 

### ISSUE THREAD

**Issue by smarijic** [lagom/online-auction-scala#57]
I am new to Lagom.
Can someone explain me why there is duplication of same events (AuctionStarted, AuctionFinished, etc.) in item-impl while same events exist in item-api.

Thanks

**Comment by renatocaval** [comment]
@smarijic The idea is to not leak the events from your domain to the external world. The API events are intended to be consumed by other services and you should keep your internal implementation decoupled from the external API to allow you to refactor it without impacting the consumers of your API.

It may look like an unnecessary overhead. Especially when the events (internal and API) share exactly the same data. It may look like pure duplication, but in fact is about building an anti-corruption layer around your internal domain. That's the main principle behind it. Of course, you may choose to not abide by it.

**Comment by renatocaval** [comment]
@smarijic I'm closing this issue, as it was more a question. It's preferable to ask questions on our mailing list or gitter channel. We reserve GitHub issues for bug reports and change requests.
