### ISSUE TITLE
Search service api expects a request body for GET request

### ISSUE THREAD

**Issue by getmetorajesh** [lagom/online-auction-scala#69]
In SearchService.scala the search is referring to GET request at the same time expecting a request body. This cause issues when trying to execute a request from any common rest clients such as postman.

`restCall(Method.GET, "/api/search?pageNo&pageSize", search _),`

Changing this to POST works pretty well, 

`restCall(Method.POST, "/api/search?pageNo&pageSize", search _),`

**Comment by botekchristophe** [comment]
I created a pull request for this. Please let me know what you think
#70

**Comment by ignasi35** [comment]
This is wrong on `online-auction-java` too.

**Comment by ignasi35** [comment]
Fixed in #70
