### ISSUE TITLE
Readiness probe failed: Get http://172.17.0.10:10002/platform-tooling/ready: dial tcp 172.17.0.10:10002: getsockopt: connection refused Back-off restarting failed container

### ISSUE THREAD

**Issue by bahtiyarerden** [lagom/online-auction-scala#83]
Hello,

I am trying to deploy my lagom scala project on kubernetes by following the development workflow. But i am getting this error on kubernetes dashboard:

`Readiness probe failed: Get http://172.17.0.10:10002/platform-tooling/ready: dial tcp 172.17.0.10:10002: getsockopt: connection refused Back-off restarting failed container`

There is my deployment steps:

```$ minikube delete
$ minikube start --memory 8192
$ minikube addons enable ingress
$ sbt "deploy minikube"
```

**Comment by bahtiyarerden** [comment]
Hi @igobrilhante,

You can look at the [https://discuss.lightbend.com/t/kubernetes-rbac-settings/1402/3](https://discuss.lightbend.com/t/kubernetes-rbac-settings/1402/3) for the temporary solution that we found.

**Comment by igobrilhante** [comment]
thanks @bahtiyarerden

**Comment by sourav0457** [comment]
Even I am facing the same issue with sbt-reactive-app plugin v1.4.0. Does anyone have any solutions for it?
 minikube version: v0.30.0
